version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "workshop-java-lambda-optimizations"
s3_prefix = "workshop-java-lambda-optimizations"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "DynamoDBTableName=\"Users\""
